[package]
name = "casa-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.9.0"
itertools = "0.14.0"
phf = { version = "0.11", features = ["macros"] }
strum = "0.27.1"
strum_macros = "0.27.1"
